<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <style>
    .page-break {
        page-break-after: always;
    }
    table {font-family: 'Montserrat', sans-serif;}
    </style>

    <table style="width:100%;">
      <tr>
        <td style="width: 50%;">
          <p>Billed To:</p>
           <p><h3><b>TECHCMANTIX PVT LTD</b></h3></p>
           <p>Trichy</p>
        </td>
        <td style="width: 50%;text-align: right;">
          <p>Generated By:</p>
       <p><h3><b>ISO Supporter</b></h3></p>
       <p>Company Address <br> 1234567</p>
        </td>
      </tr>
    </table>
    <hr>
    <table style="width: 100%">
      <tr><td style="font-size: 32px;color:#61b7f4;">#01</td></tr>
      <tr><td style="color:grey;font-weight: bold;">Issue Date : 13-01-2021</td></tr>
    </table>
    
    <style type="text/css">
      #invoicedata td{border:1px solid white;}
    </style>

    <table id="invoicedata" style="margin-top:90px;width: 100%;text-align: center;border-collapse:collapse;border:1px solid white;" cellpadding="10" cellspacing="10">
      <tr><td style="color:white;background: green;width:30px;">#</td><td style="background: lightgrey;">Description</td><td style="background: lightgrey;">Date</td><td style="background: darkgrey;">Amount</td></tr>
      <tr><td style="color:white;background: green;width:30px;">#</td><td style="background: lightgrey;">Description</td><td style="background: lightgrey;">Date</td><td style="background: darkgrey;">Amount</td></tr>
      <tr><td colspan="3" style="background: white;text-align: right;">Total</td><td style="background: white;border-bottom: 1px solid grey;">0.00</td></tr>
    
    </table>
    <hr style="margin-top: 50px;">
</body>
</html>
